apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vote
    tier: vote
  name: vote
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30200
    protocol: TCP
